-- SQLite schema for local dev

CREATE TABLE IF NOT EXISTS users (
  ID_User INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  Erstellungszeitpunkt DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Kategorie (
  ID_Kategorie INTEGER PRIMARY KEY AUTOINCREMENT,
  Kategorie_Name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Begriff (
  ID_Begriff INTEGER PRIMARY KEY AUTOINCREMENT,
  Begriff_Name TEXT NOT NULL UNIQUE,
  ID_Kategorie INTEGER NOT NULL,
  ID_User INTEGER NOT NULL,
  Bild BLOB,
  Status TEXT DEFAULT 'wird geprüft',
  Erstellungszeitpunkt DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (ID_Kategorie) REFERENCES Kategorie(ID_Kategorie),
  FOREIGN KEY (ID_User) REFERENCES users(ID_User)
);

CREATE TABLE IF NOT EXISTS Rechtschreibung (
  ID_Rechtschreibung INTEGER PRIMARY KEY AUTOINCREMENT,
  ID_Begriff INTEGER NOT NULL,
  Check_Rechtschreibung INTEGER DEFAULT 0,
  Fehlermeldung TEXT,
  Erstellungszeitpunkt DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (ID_Begriff) REFERENCES Begriff(ID_Begriff) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Blacklist (
  ID_Blacklist INTEGER PRIMARY KEY AUTOINCREMENT,
  Wort TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS Likes (
  ID_Like INTEGER PRIMARY KEY AUTOINCREMENT,
  ID_Begriff INTEGER NOT NULL,
  ID_User INTEGER NOT NULL,
  Erstellungszeitpunkt DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (ID_Begriff, ID_User),
  FOREIGN KEY (ID_Begriff) REFERENCES Begriff(ID_Begriff) ON DELETE CASCADE,
  FOREIGN KEY (ID_User) REFERENCES users(ID_User) ON DELETE CASCADE
);
